# Generated by Django 4.1.3 on 2022-11-17 13:23

from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to=shop.models.getFilename)),
                ('description', models.TextField(max_length=1500)),
                ('status', models.BooleanField(default=False, help_text='0-Show,1-Hidden')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('Seller_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('Seller_image', models.ImageField(upload_to=shop.models.getFilename)),
                ('age', models.IntegerField()),
                ('place', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('NIC_Number', models.CharField(max_length=12)),
                ('Phone_Number', models.CharField(max_length=15)),
                ('Email', models.CharField(max_length=150)),
                ('DOB', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('vendor', models.CharField(max_length=150)),
                ('product_image', models.ImageField(upload_to=shop.models.getFilename)),
                ('old_price', models.FloatField()),
                ('new_price', models.FloatField()),
                ('selling_price', models.FloatField()),
                ('Stock', models.ImageField(upload_to='')),
                ('description', models.TextField(max_length=1500)),
                ('status', models.BooleanField(default=False, help_text='0-Show,1-Hidden')),
                ('trending', models.BooleanField(default=False, help_text='0-defoult,1-trending')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('Catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.catagory')),
                ('Seller_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.seller')),
            ],
        ),
    ]
